int append();
int add_byte_mem_word();
int add_word_mem_word();
int add_string_mem_word();
int add_byte_mem_byte();
int add_word_mem_byte();
int add_string_mem_byte();
int exchange_strings_append();
int subract();
