void call_byte();//5
void call_word();//6
void call_skip_word();//7
void jump_byte();//8
void jump_word();//9
void jump_skip_word();//a
void saved_return();//11
void jump_byte_z();//12
void jump_word_z();//13
void jump_word_skip_z();//14
void jump_byte_nz();//15
void jump_word_nz();//16
void jump_word_skip_nz();//17
void compare_jump_byte_z();//18
void compare_jump_word_z();//19
void compare_jump_word_skip_z();//1a
void compare_jump_byte_nz();//1b
void compare_jump_word_nz();//1c
void compare_jump_word_skip_nz();//1d
