void set_form();
void clear_form();
void find_intersection_list_cur_obj();
void get_last_object_mask();
void find_intersection_list_point();
void find_intersection_list_vector();
void find_intersection_list_form();
void find_intersection_list_vector_cur_form();
void find_intersection_list_offset();
void get_form_center(byte *class, int form, short *origin);
