void store();
void store_expression();
void set_byte_mem_word();//6
void set_word_mem_word();//8
void set_string_mem_word();//a
void set_string_array_word();//c
void set_string_mem_byte();//16
void set_string_array_byte();//18
void set_byte_mem_byte();//12
void set_word_mem_byte();//14
void set_byte_array_word();//e
void set_word_array_word();//10
void set_byte_array_byte();//1a
void set_word_array_byte();//1c
