void get_byte_mem_word();//6
void get_word_mem_word();//8
void get_string_mem_word();//a
void get_string_array_word();//c
void get_byte_array_word();//e
void get_word_array_word();//10
void get_byte_mem_byte();//12
void get_word_mem_byte();//14
void get_string_mem_byte();//16
void get_string_array_byte();//18
void get_byte_array_byte();//1a
void get_word_array_byte();//1c
void get_byte_global_word(); //1e
void get_word_global_word();//20
void get_string_global();//22
void get_string_global_array_word();//24
void get_byte_global_array_word();//26
void get_word_global_array_word();//28
void get_byte_from_object();//2a
void get_word_from_object();//2c
void get_string_pointer_array();//30
void get_byte_pointer_array();//32
void get_word_pointer_array();//34
